name: 'Build → Test → Lint'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: 'Setup Gradle 8.10'
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.10'
          gradle-home-cache-cleanup: true

      - name: 'Build'
        id: build
        run: ./gradlew assembleRelease

      - name: 'Test'
        id: test
        run: ./gradlew testReleaseUnitTest

      - name: 'Lint'
        id: lint
        run: ./gradlew lintRelease
